FROM 992962979097.dkr.ecr.ap-southeast-2.amazonaws.com/openjdk-kafka-tabcorp:10-jdk_153

# directory containing build artifacts of sbt native packager (this arg is passed in build.sh)
ARG stage_dir=target/universal/stage

ENV APP_ROOT=/app
ENV TZ=Australia/Melbourne
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR $APP_ROOT

COPY PROJECT_CONFIG $APP_ROOT/PROJECT_CONFIG

# lib contains all our dependency jars
COPY target/universal/stage/lib lib

# code contains our application jar (the build.sh script moves it from lib to code folder before invoking docker build)
COPY target/universal/stage/code lib

# bin contains the launch scripts (generated by the sbt native-packager plugin)
COPY target/universal/stage/bin bin

# scripts
COPY scripts/start.sh /app/start.sh

RUN date

ENTRYPOINT ["/app/start.sh"]